name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Push to GitHub Packages
          uses: docker/build-push-action@v1
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GHCR_TOKEN }}
            registry: ghcr.io
            repository: random29/tsrv
            tag_with_ref: true